### PR TITLE
 Provide more details on release artifacts on download page 

### PR DESCRIPTION
**Pull request by mrutkows**

### CODE REVIEW

**Comment by dgrove-oss** [comment]
There are more runtimes in the 1.13 release.  You'll need to add sections for them too.

**Comment by mrutkows** [comment]
@dgrove-oss I know. Have been working with Rodric to get them copied to the release dist. folder... they were not there yesterday to reference.

**Comment by dgrove-oss** [comment]
ok.  Thanks.  The diff on the html is unreadable.

Meta comment (separate PR/issue?)  Can we simplify the downloads section to a nice simple table with one row for each component?

**Comment by mrutkows** [comment]
> ok. Thanks. The diff on the html is unreadable.
> 
> Meta comment (separate PR/issue?) Can we simplify the downloads section to a nice simple table with one row for each component?

Already beat you to that as well... already in the commit

**Comment by mrutkows** [comment]
@dgrove-oss  a snippet...
Screen Shot 2019-05-14 at 10 15 37 AM

**Comment by dgrove-oss** [comment]
Thanks.  Definitely an improvement.  I was wondering if even simpler might be easier for users to find what they want? For example https://sling.apache.org/downloads.cgi.

**Comment by mrutkows** [comment]
> Thanks. Definitely an improvement. I was wondering if even simpler might be easier for users to find what they want? For example https://sling.apache.org/downloads.cgi.

@dgrove-oss maybe next time...  already stayed up late last night and early this am to get what we have resolved to for today.

**Pull request merged**
