### PR TITLE
Update the `wsk` installation instructions

### PR DESCRIPTION
**Pull request by Juice10**
This updates the `wsk` install docs and adds in the (uncommented) brew docs so it'll be real easy to add them if we want, once brew has approved our pull request.

The docs here are a little lengthier and provide a little more help and context for users that aren't super experienced with setting a PATH in their shell. 

~Caveat: I suspect these docs will not work on Windows, however the other docs we had also gave you no help when it came to Windows users so I'm not sure if this makes it worse or not.~

### CODE REVIEW

**Comment by Juice10** [comment]
I updated the docs to include a separate version for Windows. This removes the earlier concern I had.

**Comment by pritidesai** [comment]
Hey @Juice10, do we have support for wsk CLI to download/install through brew?

**Comment by Juice10** [comment]
@pritidesai nearly, I need to apply a patch to it and then it can be merged. I'm going to work on that today: https://github.com/Homebrew/homebrew-core/pull/31231#issuecomment-415289712

**Comment by pritidesai** [comment]
Hey @Juice10 please let me whenever we are ready to merge this PR.

**Comment by Juice10** [comment]
Hey @pritidesai please merge this PR

**Comment by Juice10** [comment]
Update: I uncommented the brew docs now that wsk has been accepted in Homebrew

**Pull request merged**
