### PR TITLE
Update contributor sections to example potential areas of interest

### PR DESCRIPTION
**Pull request by mrutkows**
Clarify/detail all contributions are welcome... provide ideas where new contributors could find an area of interest that suits them.

### CODE REVIEW

**Comment by mrutkows** [comment]
Fix index to match titles in Contributor section of page.

**Comment by rabbah** [comment]
@mrutkows do you plan to also clarify our policies wrt communication channels? This was a point raised by @bdelacretaz --- if you're planning to do it great, if not, I'll put it on my q.

**Comment by mrutkows** [comment]
@rabbah Hi Rodric, i will address (hopefully today) on a separate PR if that is OK...

**Comment by rabbah** [comment]
thanks @mrutkows.

**Pull request merged**
